import BlinkingCursor from "@/components/BlinkingCursor";
import TypingEffect from "@/components/TypingEffect";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>DEAN | Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-screen">
        <nav className="px-8 py-4 flex justify-center items-center text-xl">
          <p className="font-light tracking-[0.5rem] transition-all hover:text-slate-800 cursor-pointer">
            DEAN
          </p>
        </nav>
        <section className="p-16 grow flex flex-col justify-center">
          <p className="flex items-center justify-center bg-black text-white self-start rounded-3xl px-6 py-12 tracking-[0.5rem] shadow-xl mb-8 transition-all hover:translate-y-[-0.5rem] hover:shadow-2xl">
            DEA<span className="tracking-[0]">N</span>
          </p>
          <p className="text-4xl mb-6">Hello there 👋</p>
          <p className="text-xl text-slate-700 mb-4">
            I&#39;m <span className="font-medium text-black">Dean</span>,{" "}
            <TypingEffect
              text={[
                "a 17-years-old. ",
                "a junior programmer. ",
                "a high school student. ",
                "who interested in AI recently. ",
                "a Mathematics/Physics enthusiast. ",
              ]}
              typingSpeed={100}
              erasingSpeed={50}
              delay={1000}
            />
            <BlinkingCursor />
          </p>
          <a className="text-lg px-6 py-3 bg-blue-200 text-slate-800 self-start rounded-lg transition-all cursor-pointer hover:bg-blue-100">
            Learn more
          </a>
        </section>
        <section>
          <nav className="px-8 py-4 flex justify-center items-center text-xl">
            <p className="text-base text-slate-500">Discord: Dean#9500</p>
          </nav>
        </section>
      </main>
    </>
  );
}
